### ISSUE TITLE
Pass default request options to the HTTP client

### ISSUE THREAD

**Issue by pimolo** [Nekland/BaseApi#9]
For a lib I'm developing, I'm using BaseApi.
I have to disable the SSL certificate validation.
According to the Guzzle Client doc (I'm using Guzzle), I have to pass the following configuration to the constructor:

``` php
[
    'defaults' => [
        'verify' => false
    ]
]
```

So I pass that into HttpClientFactory. But in GuzzleAdapter, these options seems to be never passed into the Client's constructor.
I understand how `base_url` and `user_agent` can be read, but what if I want to set more config ?
Like here? https://github.com/guzzle/guzzle/blob/4.2.3/docs/clients.rst#request-options

**Comment by Nek-** [comment]
You can create a new "[Adapter](https://github.com/Nekland/BaseApi/blob/master/lib%2FNekland%2FBaseApi%2FHttp%2FAbstractHttpClient.php)" (client) or make a PR because options to guzzle are not currently supported.
